services:
  nextjs-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-dev
    restart: unless-stopped
    init: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - DMR_HOST=http://model-runner.docker.internal
      - DMR_MODEL=ai/llama3.2:latest
    networks:
      - appnet
    depends_on:
      - ai_runner

  ai_runner:
    provider:
      type: model
      options:
        model: ai/llama3.2:latest

networks:
  appnet:
    driver: bridge
